language: node_js  

node_js:
 - "7"

addons:
 chrome: stable

before_script:
  - npm install
  - npm build

after_failure:
  - cat /TabSolution/travisBugs.log
  
before_deploy:

deploy:

branches:
  only:
  - travis
  
script:
  - build: tsc server.ts
  - npm test

